name: Maven Package and Docker Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # For GitHub Container Registry

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Maven 3.9.2
      run: |
        wget https://archive.apache.org/dist/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
        tar -xzf apache-maven-3.9.2-bin.tar.gz
        sudo mv apache-maven-3.9.2 /usr/local/apache-maven
        echo "MAVEN_HOME=/usr/local/apache-maven" >> $GITHUB_ENV
        echo "PATH=/usr/local/apache-maven/bin:$PATH" >> $GITHUB_ENV

    - name: Verify Maven version
      run: mvn -v

    - name: Get current version
      id: get_version
      run: |
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "VERSION=${version}" >> $GITHUB_ENV
        echo "VERSION=${version}"

    - name: Update version in pom.xml
      run: |
        new_version=$(echo $VERSION | awk -F '-' '{print $1}' | awk -F '.' '{print $1 "." $2 "." ($3+1) "-SNAPSHOT"}')
        mvn versions:set -DnewVersion=$new_version
        mvn versions:commit
        echo "NEW_VERSION=${new_version}" >> $GITHUB_ENV
        echo "NEW_VERSION=${new_version}"

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Build Docker image
      run: |
        docker build -t hadarkravetsky/hello_world:${{ env.NEW_VERSION }} .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: |
        docker push hadarkravetsky/hello_world:${{ env.NEW_VERSION }}

    - name: Publish to GitHub Packages
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload JAR to GitHub Actions
      uses: actions/upload-artifact@v3
      with:
        name: my-app-jar
        path: target/*.jar
